### ISSUE TITLE
Leftover schema definitions in Postgres after Liquibase migration

### ISSUE THREAD

**Issue by romasch** [ayedo/jooq-modelator#5]
When running migrations with Liquibase, Postgres and multiple schemas, the database is not properly cleaned up after each run. 

Reproduction steps:
1) Set up example project with the following Liquibase databaseChangeLog.yml:
```
databaseChangeLog:
    - changeSet:
        id: 1
        author: test
        changes: [sql: {sql: "create schema test"}]
#    - changeSet:
#        id: 2
#        author: test
#        changes: [empty: {}]
```
1) Run liquibase migration.
2) Uncomment the second changeset and run again.
=> Change Set scripts/databaseChangeLog.yml::1::test failed.  Error: ERROR: schema "test" already exists [Failed SQL: create schema test]

The problem is the statement `liquibase.dropAll()`, which only deletes the default (public) schema.

There are multiple solutions to this:
1) Never reuse a container, instead create a new one every time (and delete it afterwards).
2) Add plugin configuration options for schemas to be deleted in Liquibase.
3) Never delete the database in an existing container, but instead add a task to delete the container from Gradle.

Personally I think the first solution is the easiest with least risk of future headache. There might be a slight performance impact, but since the plugin only runs when there are actual changes to the changelog this might not be such an issue.
